
@server = localhost
@port = 10000
@baseUrl = http://{{server}}:{{port}}

@server_onrender = https://home-broker.onrender.com/
@port = 10000
@baseUrl_onrender = http://{{server_onrender}}
//:{{port}}

### Get Users
GET {{baseUrl}}/assets/
content-type: application/json


### Get Users
GET {{baseUrl_onrender}}/assets/
content-type: application/json

###

POST http://localhost:10000/assets/
content-type: application/json

{
    //"name"  : "Amazon",
    //"symbol": "A1",
    //"price" : 100,
    //"image" : "AMZN.png"
}

###

### Example API call
#GET {{API_SERVER}}:{API_PORT}/assets/ HTTP/1.1

###

GET http://localhost:10000/assets/ HTTP/1.1

###

GET http://localhost:10000/assets/:1 HTTP/1.1

###
PATCH http://localhost:10000/assets/:1 HTTP/1.1
content-type: application/json

{
    //"name"  : "Amazon",
    //"symbol": "A1",
    //"price" : 100,
    //"image" : "AMZN.png"
}

###
DELETE http://localhost:10000/assets/:1 HTTP/1.1
content-type: application/json

{
    //"name"  : "Amazon",
    //"symbol": "A1",
    //"price" : 100,
    //"image" : "AMZN.png"
}

###

POST http://localhost:10000/assets/
content-type: application/json

{
    //"name"  : "Amazon",
    //"symbol": "A1",
    //"price" : 100,
    //"image" : "AMZN.png"
}